name: Azure Deployment

on:
  workflow_dispatch:
  # Run the workflow on commit to main branch
  push:
    # Run when commits are pushed to mainline branch
    # Set this to the mainline branch you are using
    branches:
      - main

  # Using client credentials (service principal) authentication
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # azd build-in variables for client credentials authentication
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      # OpenAI configuration
      OPENAI_NAME: ${{ vars.OPENAI_NAME }}
      OPENAI_RESOURCE_GROUP_NAME: ${{ vars.OPENAI_RESOURCE_GROUP_NAME }}
      EMAIL_RECIPIENT_ADDRESS: ${{ vars.EMAIL_RECIPIENT_ADDRESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # using the install-azd action
      - name: Install azd
        uses: Azure/setup-azd@v2.1.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Login with service principal (client credentials)
      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          az login --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

      - name: Set environment variables
        run: |
          if [ ! -z "${{ vars.AZURE_AI_FOUNDRY_ENDPOINT }}" ]; then
            azd env set AZURE_AI_FOUNDRY_ENDPOINT "${{ vars.AZURE_AI_FOUNDRY_ENDPOINT }}"
          fi
          if [ ! -z "${{ vars.AGENT_ID }}" ]; then
            azd env set AGENT_ID "${{ vars.AGENT_ID }}"
          fi
          if [ ! -z "${{ vars.USE_FOUNDRY_AGENT }}" ]; then
            azd env set USE_FOUNDRY_AGENT "${{ vars.USE_FOUNDRY_AGENT }}"
          fi

      - name: Provision Infrastructure and Deploy Application
        run: azd up --no-prompt
        shell: bash
        env:
          # uncomment this if you are using infrastructure parameters
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
