on:
  workflow_dispatch:
  # Run the workflow on commit to main branch
  push:
    # Run when commits are pushed to mainline branch
    # Set this to the mainline branch you are using
    branches:
      - main

  # Using client credentials (service principal) authentication
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # azd build-in variables for client credentials authentication
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      ## Define the additional variables or secrets that are required globally (provision and deploy)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # using the install-azd action
      - name: Install azd
        uses: Azure/setup-azd@v2.1.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Login with service principal (client credentials)
      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          az login --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        shell: pwsh
        env:
          # uncomment this if you are using infrastructure parameters
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
          ## Define the additional variables or secrets that are required only for provision

      - name: Deploy Application
        run: azd deploy --no-prompt
        shell: pwsh
        # env:
        ## Define the additional variables or secrets that are required only for deploy
